# Setup
title:               ecoslacker
tagline:             'Programming and Linux ramblings'
description:         'I am a PhD student of Biosystems Engineering, in this site I describe how I manage to work with Linux'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              ecoslacker
  url:               http://irriapps.com/
  email:             ecoslacker@irriapps.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
